### ISSUE TITLE
Avoid hardcoded default in library

### ISSUE THREAD

**Issue by Mikkeren** [emiln/slacker#10]
Perhaps the hardcoded ID to the Dongers Inc #srsbsns channel isn't the most meaningful default.
https://github.com/emiln/slacker/blob/master/src/slacker/converters.clj#L31

I would probably prefer that there wasn't a default and having to specify the channel, to avoid unintended behavior.

This would of course mean the library should support some easy way to look up the channel ID from name, or from the message it received.

**Comment by emiln** [comment]
I agree that hard-coding the channel isn't really sensible for a library. It made more sense back when this was all part of a specific bot. I still think handling `id` and `type` by default (but allowing you to override it) is what most people will want. I'm removing the default channel and will provide `slacker.lookups/channels`, which is a function from string-token to channel-list, returning all channels visible given the token.

**Comment by emiln** [comment]
Given the above, you already have the channel ID if you `handle` a `:message` event, and if not you can find a channel ID along the lines of:

``` clojure
(->> (channels "my-token")
  (filter #(= "srsbsns" (:name %)))
  (first)
  (:id))
```
