### ISSUE TITLE
Decide on event naming convention

### ISSUE THREAD

**Issue by emiln** [emiln/slacker#3]
A few suggestions:
## _subject_-_(past tense) verb_
-   `:connection-failed`
-   `:connection-succeeded`
-   `:message-sent`
## _subject_-_noun_
-   `:connection-failure`
-   `:connection-success`
-   `:message-transmission`

**Comment by Mikkeren** [comment]
I would prefer the _subject_-_noun_ naming as they do not convey a certain state for the action, which would be passed as data anyway to any relevant handlers.

**Comment by emiln** [comment]
I'm somewhat conflicted. I haven't fully formalized message sending yet, but let's look at an imagined way to handle a full message transmission:

## _subject-noun arg_
-   The bot calls `(emit! :message-transmission :send "hay guise")`.
-   The client picks up on `:message-transmission` and deduces from the arguments that it's a request to send a message. It transmits the message over the websocket.
-   The client picks up on the `reply_to` event on the websocket and knows that a message has been delivered.
-   The client calls `(emit! :message-transmission :delivered 123)` to let the bot know that the message with id 123 was successfully delivered.
-   The client picks up on the `message` event on the websocket, as its own message is now being sent to all users on the channel, including the bot.
-   The client calls `(emit! :message-transmission :received msg)` to let the bot know that a message has been received.

The bot (handling `:message-transmission`) sees:
-   `:message-transmission :send`
-   `:reply_to` _if it wants to_
-   `:message-transmission :delivered`
-   `:message-transmission :received`

It's unclear how many of the events (if any) the bot is really interested in. It can of decide to not handle `message-transmission` at all, but the granularity is quite rough.

## _subject-verb_
-   The bot calls `(emit! :message-send "hay guise")`.
-   The client picks up on `:message-send` and transmits the message over the websocket.
-   The client picks up on the `reply_to` event on the websocket and knows that a message has been delivered.
-   The client calls `(emit! :message-delivered 123)` to let the bot know that the message with id 123 was successfully delivered.
-   The client picks up on the `message` event on the websocket, as its own message is now being sent to all users on the channel, including the bot.
-   The client calls `(emit! :message-received msg)` to let the bot know that a message has been received.

The bot (handling zero or more of the following) sees:
-   `:message-send` _if it wants to_
-   `:reply-to` _if it wants to_
-   `:message-delivered` _if it wants to_
-   `:message-received` _if it wants to_

It's now entirely up to the bot to handle the events it wants. This will lead to potentially many, but rather simple, handlers. The granularity is very fine, but perhaps bot authors might be daunted by the number of unique events.

**Comment by Mikkeren** [comment]
Considering this, I would probably prefer _subject_-_verb_. That way handlers are simpler and thus have less information to filter through for simple events.

With that setup a thorough description of the various connections between the events is a requirement though, as the connections are less obvious.

But I'm all for letting bot developers decide how many events they want to handle, and that's easiest with the second approach. That leaves them free to write a single function to handle all three and call that from three handlers.

With the _subject_-_noun_ approach, this is not an option, but a requirement. And only handling single events is not a possibility.

**Comment by emiln** [comment]
I agree. Perhaps a few simple conventions would help even further:

## Commands

An event calling out for something to happen. The expectation is that another well-known handler will actually be listening for this event and will carry out some computation or IO, the result of which should later be reported.

### Naming convention: _noun-(imperative) verb_

Examples:
- `:message-send`
- `:connection-close`
- `:user-kick`
- `:channel-leave`

## Reports

An event signalling that something happened, and that someone might find this of interest. This does not necessitate action, and nothing bad will happen if no one sees or acknowledges the event.

### Naming convention: _noun-(past tense) verb_

Examples:
- `:message-sent`
- `:connection-closed`
- `:user-kicked`
- `:channel-left`

**Comment by emiln** [comment]
My big worry is that commands and reports will look too similar. We could of course also opt for a command naming convention along the lines of:
- `:send-message`
- `:close-connection`
- `:kick-user`
- `:leave-channel`

This has problems of its own, though.

**Comment by Mikkeren** [comment]
Either that or simply namespace action-events and reaction-events to have a clear distinction.

That way users can import the namespace if they feel man enough to handle separating them mentally, and others can simply include the identifier to make the distinction clear.

**Comment by emiln** [comment]
I wish GitHub had a vote feature built in so I could outsource decision-making and general responsibility. I bet I will end up regretting this regardless of which naming convention we choose.

**Comment by emiln** [comment]
I'm still rather torn.

`:send-message` -> `:message-sent` gives a good visual distinction when quickly reading blocks of code between the two, but in return I've dictated a rather arbitrary naming convention that is mostly inspired by aesthetics. If I'm consistent in using it, I still think it should be easy to figure out what a given event is called, though.

`:slacker.commands/message-send` -> `:slacker.reports/message-sent` is very precise and specific, which is great, but the non-namespace parts still look very similar, which might cause people to mistake one for the other every now and then. There's also the matter of people having to remember to use the right namespace, or the event will just silently be ignored. It's hard to tell whether this will actually be annoying for bot authors.

**Comment by emiln** [comment]
I am going forward with:

| Event type | Naming convention | Example |
| --- | --- | --- |
| Commands | _(imperative verb)-noun_ | `:connect-websocket` |
| Reports | _noun-(past tense verb)_ | `:websocket-connected` |
