### ISSUE TITLE
slacker.client/receive-message seems passes no arguments

### ISSUE THREAD

**Issue by supermomonga** [emiln/slacker#44]
I created a test branch of my slacker sample repository.

https://github.com/supermomonga/sample-slacker-pingpong/blob/1cc8a047b670c5ba1a66fd8afe3f4570e50c4dd8/src/sample_slacker_pingpong/core.clj#L16-L20

It tries to print passed args when some events happened (hello, message...).

I expect [some arguments will be passed](https://github.com/emiln/slacker/blob/841c542c65ae8d2a2191022bab4a4dcf5102def5/src/slacker/client.clj#L110) but it seems always passed no argument.

Here is the log when I run a bot with `lein run` command and tried some actions in my personal slack team's channel which have two members, bot and me.

```
hello args: nil
message args: nil
pin-added args: nil
message args: nil
pin-removed args: nil
```

**Comment by emiln** [comment]
I am rather flabbergasted by this. You are completely right, and I now wonder when I managed to introduce this crippling bug. My most recent "production level" bot runs on Slacker 1.2.0 so at least there aren't too many commits to look into.

Getting #35 implemented would probably be a good idea as I bet it would have caught this much sooner. I expect it's one of my most recent additions that have broken things.

I'll have a look at it Sunday.

**Comment by supermomonga** [comment]
Hi. I figured out what the problem is, and will send a Pull Request today!
