### ISSUE TITLE
More useful examples in README

### ISSUE THREAD

**Issue by emiln** [emiln/slacker#5]
I think the README should contain a simple (already has) and intermediate (lacking) example of using `emit!`/`handle` to actually achieve something. The examples should implement concepts that are relevant to bot authors.

**Ideas**:
- Keep track of how often many messages the different users have sent and send this information to a channel when requested. **(Intermediate)**
- Reprimand users when they use lewd language. **(Simple)**

**Comment by Mikkeren** [comment]
How about maybe reprimanding users with varying different moods, like introducing simple typos and upper case letters based on how many times in a specified timespan the user violates the language restrictions?
I suppose that would count as intermediate as well.

**Comment by emiln** [comment]
That's a nice idea. I think the easiest trigger would be profanity. The great part would be the bot eventually using profane language itself as it grows sufficiently angry.

**Comment by Mikkeren** [comment]
It would also introduce a certain aspect of synchronicity since the bot would have to keep track of whether or not the profanity was of its own doing. (Though I suppose just keeping track of its own User ID could do that as well.)
