### ISSUE TITLE
Facilitate user lookups

### ISSUE THREAD

**Issue by emiln** [emiln/slacker#7]
It would be nice to ask queries like "what's the full name of the user with this ID?".

**Comment by Mikkeren** [comment]
Similarly asking for a User ID based on a username, might also be useful. (Since highlighting looks like it needs both ID and username)

**Comment by emiln** [comment]
Absolutely. I imagine you'll just get all info about a user in a map.

**Comment by emiln** [comment]
I think this could be handily solved along the lines of what's proposed for #10. That is, 

``` clojure
(slacker.lookups/users "my-token")
```

will return all users visible given the token, and will cache its result. Cache-invalidation should happen when users join or leave.
